### ISSUE TITLE
Redirects: Uncaught Error: Not running

### ISSUE THREAD

**Issue by Zev23** [visionmedia/supertest#129]
I'm having this error when using 1 or more redirects.
This error occurs in supertest v0.11.0.
supertest v0.10.0 doesn't have this error.

node version 0.11.12.

Test case:
```
describe('Redirects', function() {
    it('should work', function(done) {
        var app = express();
        app.get('/', function(req, res) {
            res.redirect('/r1');
        });
        app.get('/r1', function(req, res) {
            res.send(200);
        });

        request(app)
            .get('/')
            .redirects(1)
            .expect(200, done);
    });
});
```

Error log:
```
  1) Redirects should work:
     Uncaught Error: Not running
      at Server.close (net.js:1344:11)
      at /home/action/workspace/app/node_modules/supertest/lib/test.js:126:36
      at Test.Request.callback (/home/action/workspace/app/node_modules/supertest/node_modules/superagent/lib/node/index.js:660:30)
      at Test.<anonymous> (/home/action/workspace/app/node_modules/supertest/node_modules/superagent/lib/node/index.js:132:10)
      at Test.EventEmitter.emit (events.js:104:17)
      at IncomingMessage.<anonymous> (/home/action/workspace/app/node_modules/supertest/node_modules/superagent/lib/node/index.js:818:12)
      at IncomingMessage.EventEmitter.emit (events.js:126:20)
      at _stream_readable.js:895:16
      at process._tickCallback (node.js:339:11)
```

**Comment by alekbarszczewski** [comment]
+1, So when pull will be merged? I am facing same issue...

**Comment by alekbarszczewski** [comment]
Added pull request with fix and test. Please merge #286. Thanks.

**Comment by serby** [comment]
:+1: It would be uber handy for this to be fixed.
