### ISSUE TITLE
`Cannot call method 'call' of undefined` when running 2 supertest tests in a row.

### ISSUE THREAD

**Issue by jtremback** [visionmedia/supertest#201]
I have 2 tests which both contain the following code:

```js
  request(app)
    .post('/user?foo=bar')
    .send({ foo: 'bar' })
    .end()
```
I get this error when running both, but it goes away if I comment either one.

```js
TypeError: Cannot call method 'call' of undefined
    at Test.assert (/Users/jehan/platform_UIlogger/node_modules/supertest/lib/test.js:221:6)
    at assert (/Users/jehan/platform_UIlogger/node_modules/supertest/lib/test.js:132:12)
    at g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1276:10
    at process._tickCallback (node.js:419:13)
```

**Comment by kevinawoo** [comment]
`.end()` needs to be passed a function

```
request(app)
    .post('/user?foo=bar')
    .send({ foo: 'bar' })
    .end(function(err, response) {
        // errors are logged in error or null
        // response object
})
```

**Comment by jtremback** [comment]
Oh.
