### ISSUE TITLE
version 1.0.0 error when testing error statuses

### ISSUE THREAD

**Issue by Olgagr** [visionmedia/supertest#226]
I'm trying to test that endpoint returns 403 status. The test looks like:

```
      it 'returns 401 status', (done) ->
        global.$request(app)
          .post("#{basicPath}/login/facebook")
          .type('json')
          .expect(401, done)
```

When I'm run this test I get:

```
  1) users routes POST /login/facebook when facebook token is not send with request returns 401 status:
     Error: Unauthorized
    at _stream_readable.js:908:16
  
npm ERR! Test failed.  See above for more details.
```
This is wrong as test should pass as application returns 401 status (checked in the browser).

When I change tested status to 404:

```
  1) users routes POST /login/facebook when facebook token is not send with request returns 401 status:
     Error: expected 401 "Unauthorized", got 404 "Not Found"
    at net.js:1409:10
```
And this is correct, this test should failed and the message is correct.

I downgrade the supertest version to 0.15.0 and after that test passes. So there is something wrong with version 1.0.0.

**Comment by Olgagr** [comment]
Duplicate: #225 

For version 1.0.0 the test should look like:

```
      it 'returns 401 status', (done) ->
        global.$request(app)
          .post("#{basicPath}/login/facebook")
          .type('json')
          .expect(401)
          .end (err, res) ->
            if (err)
              return done(err)
            done()
```
