### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by crypti** [visionmedia/supertest#248]
I have problem with supertest. I run api tests. Sometimes some random tests send me this error.

```javascript
    Uncaught TypeError: undefined is not a function
     at Socket.socketOnEnd [as onend] (http.js:1572:9)
     at _stream_readable.js:943:16
```

Example of one test:
```javascript
  it(test + '. We attempt to upVote same delegate SEVERAL TIMES from random account. We expect error',function(done){
           var votedDelegate = '"+' + node.Eaccount.publicKey + '","+' + node.Eaccount.publicKey + '"';
           setTimeout(function(){
               node.api.put('/accounts/delegates')
                   .set('Accept', 'application/json')
                   .send({
                       secret: Raccount.password,
                       delegates: [votedDelegate]
                   })
                   .expect('Content-Type', /json/)
                   .expect(200)
                   .end(function (err, res) {
                       console.log(res.body);
                       node.expect(res.body).to.have.property("success").to.be.false;
                       node.expect(res.body).to.have.property("error");
                       done();
                   });
           }, 1000);
       });
```

Then all other tests run good. is it some problem of supertest?

**Comment by JimFung** [comment]
@crypti did you ever find a solution to this problem?

**Comment by kmbauer** [comment]
Can you provide more information on what the error/solution was?
