### ISSUE TITLE
.connect method has no status property?

### ISSUE THREAD

**Issue by JaKXz** [visionmedia/supertest#296]
I have an express app that I start in my `beforeEach` method (and close in my `afterEach` method), which defines the [connect](http://expressjs.com/4x/api.html#app.METHOD) method handler as follows:

```js
app.connect('/*', (req, res) => {
  res.status(405).end();
});
```

My test code looks like this:

```js
it('should not allow CONNECT requests', () => {
  request(server)
    .connect('/')
    .expect(405, done);
});
```
and throws this error:

```bash
     TypeError: Cannot read property 'status' of undefined
      at Test._assertStatus (node_modules/supertest/lib/test.js:229:10)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:781:12)
      at ClientRequest.<anonymous> (node_modules/superagent/lib/node/index.js:736:10)
      at Socket.socketOnEnd (_http_client.js:294:9)
      at endReadableNT (_stream_readable.js:905:12)
```

I also have a similar handler defined for every other method in the node http module's `METHODS` array except POST, and the tests for all of the other methods pass. Any ideas?

**Comment by JSteunou** [comment]
Same here, I find out that happens only with express-session and option `saveUninitialized` on `true` (actual default) if set on `false` it's worse, request get on hold and timeout.

**Comment by mikelax** [comment]
I think this is specific to the actual CONNECT Method and not an issue with supertest. 
CONNECT seems to be used specifically for [SSL tunneling](http://www.checkupdown.com/status/E405.html).
