### ISSUE TITLE
Expect Status with `done()` isn't working

### ISSUE THREAD

**Issue by dmolineuxcb** [visionmedia/supertest#345]
`.expect(404, done)` doesn't seem to be failing if the response is actually 200. Not sure if I'm doing something wrong, or if I've found a bug?

http://stackoverflow.com/questions/37729206/supertest-expect-not-asserting-status-codes-correctly

**Comment by saintedlama** [comment]
Works for me as expected. Simple test with an empty express app

```js
    it('should handle an 404 response in expect callback', function (done) {
      var app = express();

      request(app)
      .get('/')
      .timeout(1)
      .expect(404, function (err) {
        err.should.be.an.instanceof(Error);
        done();
      });
    });
```

**Comment by dmolineuxcb** [comment]
Thx for the reply @saintedlama yes your code seems to work, but the test passes if I add an `expect(200,done)`. Like this:
```
		it('should handle an 404 response in expect callback', function (done) {
			request(app)
			.get('/doesntExist')
			.timeout(1)
			.expect(404, function (err) {
				console.log("yep")
				done();
			});
		});

		it('should handle an 404 response in expect callback', function (done) {
			request(app)
				.get('/doesntExist')
				.timeout(1)
				.expect(200, done);
		});
```

**Comment by saintedlama** [comment]
What does the `timeout` function do? Never saw that in supertest :dizzy_face: 

Could you try to remove the `timeout` function calls and see what happens? Works on my machine (windows) like a charm without timeout calls

**Comment by dmolineuxcb** [comment]
Lol sorry ill take it out! not sure what it does either, copied it from your example there :)
```
        it('should handle an 404 response in expect callback', function (done) {
            request(app)
            .get('/doesntExist')
            .expect(404, function (err) {
                console.log("yep")
                done();
            });
        });

        it('should handle an 404 response in expect callback', function (done) {
            request(app)
                .get('/doesntExist')
                .expect(200, done);
        });
```
So on windows, the second unit test produces an error?

**Comment by saintedlama** [comment]
This code

```js
  it('should handle an 404 response in expect callback', function (done) {
    var app = express();
    request(app)
      .get('/doesntExist')
      .expect(404, function (err) {
        console.log("yep")
        done();
      });
  });

  it('should handle an 404 response in expect callback', function (done) {
    var app = express();
    request(app)
      .get('/doesntExist')
      .expect(200, done);
  });
```

produces that error

```
  1) request(app) should handle an 404 response in expect callback:
     Error: expected 200 "OK", got 404 "Not Found"
      at Test._assertStatus (C:\p\supertest\lib\test.js:259:12)
      at Test._assertFunction (C:\p\supertest\lib\test.js:274:11)
      at Test.assert (C:\p\supertest\lib\test.js:157:18)
      at Server.assert (C:\p\supertest\lib\test.js:131:12)
      at emitCloseNT (net.js:1549:8)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

Btw: I'm using supertest 1.2

**Comment by dmolineuxcb** [comment]
Thats the behavior I would expect!
From my package json
```
"supertest": "^1.2.0"
```
I'm on a mac, not sure exactly why this is happening :(

**Comment by mikelax** [comment]
@dmolineuxcb  I just tested the above code on a mac and I am also getting the correct behavior, first test passes and second fails. 

Please run this code snippet

```javascript
var express = require('express');
var request = require('supertest');

describe('Test expect status code with done param', function() {
  it('should handle an 404 response in expect callback', function (done) {
    var app = express();
    request(app)
      .get('/doesntExist')
      .expect(404, function (err) {
        console.log("yep")
        done();
      });
  });

  it('should handle an 404 response in expect callback', function (done) {
    var app = express();
    request(app)
      .get('/doesntExist')
      .expect(200, done);
  });
});
```

**Comment by dmolineuxcb** [comment]
```Dougs-MacBook-Pro:new-api dougmolineux$ cat spec/test-spec.js 
var express = require('express');
var request = require('supertest');

fdescribe('Test expect status code with done param', function() {
  it('should handle an 404 response in expect callback', function (done) {
    var app = express();
    request(app)
      .get('/doesntExist')
      .expect(404, function (err) {
        console.log("yep")
        done();
      });
  });

  it('should handle an 404 response in expect callback', function (done) {
    var app = express();
    request(app)
      .get('/doesntExist')
      .expect(200, done);
  });
});
Dougs-MacBook-Pro:new-api dougmolineux$ npm test

> node-api@1.0.0 test /Users/dougmolineux/dev/new-api
> jasmine

Started
yep
.Connected correctly to database, listening to post 3000
.


Ran 2 of 243 specs
2 specs, 0 failures
Finished in 0.096 seconds
Dougs-MacBook-Pro:new-api dougmolineux$ ```

**Comment by dmolineuxcb** [comment]
"Connected correctly to database, listening to post 3000" is coming from my app.js file. 

I think it must be related to a version of something that I'm using, node v6.1.0 jasmine, 

"jasmine": "^2.4.1",
"express": "^4.13.4",

**Comment by dmolineuxcb** [comment]
Not a huge deal, I'll just refactor all the tests and add an `end` with a `done()` inside it. It will probably come up again I suspect :)

**Comment by bradwbradw** [comment]
I'm running `supertest 2.0.0` and copying the exact code pasted here: https://github.com/visionmedia/supertest/issues/345#issuecomment-229496425

Both tests pass, so it seems like a breaking change was introduced in 2.0.0, maybe i'm missing something in the docs, but i'm not sure what to do to test the status code

**Comment by rpadovani** [comment]
I have the same problem:

This doesn't fail:

```
request(app)
				.get('/labels')
				.expect(202, [validLabel, anotherValidLabel], done);
```

while this fails:

```
request(app)
				.get('/labels')
				.expect(202, [validLabel, anotherValidLabel])
				.end(err => err ? done.fail(err) : done());
```

**Comment by CarlosCuevas** [comment]
experiencing same issue as @rpadovani and @bradwbradw

**Comment by pbalan** [comment]
Same here.
