### ISSUE TITLE
Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by re-jim** [visionmedia/supertest#376]
Possibly related to #352 

Node v0.10.36
Supertest version v2.0.0
Test's error message:
"http-module::encode-route."after each" hook"

Stack trace:

```
Cannot set property 'state' of undefined
TypeError: Cannot set property 'state' of undefined
    at Test.<anonymous> (test/modules/http/routes/encode-route-test.js:161:40)
    at Test.assert (node_modules/supertest/lib/test.js:156:6)
    at assert (node_modules/supertest/lib/test.js:127:12)
    at node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
    at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
    at _stream_readable.js:944:16
```

The test:

```
it.only('should respond with a status of 200 if the params are correct', function (done) {
            request(api)
                .get('/url', function (req, res) { })
                .expect('Content-Type', 'application/json; charset=utf-8')
                .expect(200)
                .end(function(err,res){done()});
        });
```

Line 141 is the line starting with .end

Also, I get this:

```
http-module::encode-route."before each" hook
 Stack Trace
expected false to be true
```

Which is weird, because I don't "expect" anything in the "before each" hook.

**Comment by mikelax** [comment]
@re-jim  do you want to update to 2.0.1 and see if that version resolves this issue?

**Comment by bananaappletw** [comment]
I met the similar problem of this issue.
But the request is `.head`

**Comment by bananaappletw** [comment]
I met similar problem of this issue.
But, the request is `HEAD`

**Comment by gxsfdcpractice** [comment]
seems like this should be closed
