### ISSUE TITLE
get request with queryString "成都" will throw a confusing error.

### ISSUE THREAD

**Issue by azathothes** [visionmedia/supertest#384]
the code is very simple , but confusing:
```
var request = require('supertest');
var express = require('express');
 
var app = express();
 
app.get('/user', function(req, res) {
  res.status(200).json({isok:true,mesg:"success!"});
});

describe('GET /user', function() {
  it('respond with json', function(done) {
    request(app)
      .get('/user?ac=成都')
      .set('Accept', 'application/json')
      .expect('Content-Type', /json/)
      .expect(200, done);
  });
});
```

this code works with mocha. when i ran mocha test.js , if querystring "ac" equals “成都” it will throw the error as follows:

``` TypeError: Cannot read property 'header' of undefined```

detail error stack:

``` 1) GET /user respond with json:
    TypeError: Cannot read property 'header' of undefined
     at Test._assertHeader (node_modules\supertest\lib\test.js:232:19)
     at Test._assertFunction (node_modules\supertest\lib\test.js:281:11)
     at Test.assert (node_modules\supertest\lib\test.js:171:18)
     at Server.assert (node_modules\supertest\lib\test.js:131:12)
     at emitCloseNT (net.js:1525:8)
```

I'v tested the other chinese charactor and it's ALL OK but "成都".

os : windows 7
mocha : 3.2.0
supertest: 2.0.1

i know this is a stupid issue but any ideas or tips would be apperciated!

( ゜- ゜)つロ thanks!

**Comment by azathothes** [comment]
Should'v use ```query({ac:"成都"})``` instead of  ```/user?ac=成都```.
