### ISSUE TITLE
Cannot handle uncaught error

### ISSUE THREAD

**Issue by rupamroy** [visionmedia/supertest#415]
Hi, 

Here is my module under test

```typescript
import express = require('express');
import { healthCheck } from '../services/health-check';

let router = express.Router();

router.get('/', (req, res, next) => {
    return healthCheck.get()
        .then((data) => {
            res.status(200).send(data);
        })
        .catch((err) => {
            res.status(500).send('healthcheck failed');
            next(err);
        });
});

export const healthCheckRouter = router;
```

And here is the test which is testing the service err case
```typescript
describe('when service throws an error', () => {
        let app;
        beforeEach(() => {
            app = express();
            healthCheckServiceFake.healthCheck.get.returns(Promise.reject(new Error()));
            app.use('/api/healthcheck', moduleUnderTest.healthCheckRouter);
            app.use((err, req, res, next) => {
                res.end();
            });

        });
        it('should respond with a 500 status', (done) => {
             request(app)
                .get('/api/healthcheck')
                .expect(500)
                .end((err, res) => {
                    done();
                });
        });
    });
```

The `healthCheckServiceFake.healthCheck.get` is a `sinon` stub injected using `mockery`. 

The problem I am facing is the test case does pass , but it dumps the uncaught error into the test console.

```bash
 Health Check Router
    The module
      ✓ should exist
    when service returns data
      ✓ should respond with a 200 status
    when service throws an error
Unhandled rejection Error
    at Context.<anonymous> (/Users/430014695/Projects/test-gnw-angular/server/routes/health-check.router.spec.ts:82:75)
    at callFn (/Users/430014695/Projects/test-gnw-angular/node_modules/mocha/lib/runnable.js:345:21)
    at Hook.Runnable.run (/Users/430014695/Projects/test-gnw-angular/node_modules/mocha/lib/runnable.js:337:7)
    at next (/Users/430014695/Projects/test-gnw-angular/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/Users/430014695/Projects/test-gnw-angular/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

      ✓ should respond with a 500 status


  27 passing (1s)

```

Please help if anyone knows how to handle this error.

**Comment by mtrunt** [comment]
I'm facing a similar issue trying to test a loopback endpoint, using Bluebird for promises.

This is the remote method's code (simplified):
```javascript
Model.remoteMethod = (arg, next) => {
  return new Promise((resolve, reject) => {
    if (arg.rs.length <= 0) {
      reject(new Error('No results'))
    }

    resolve(rs)
  }).catch(error => {
   throw error
  })
}
```

After running the test I get a similar output (unhandled error for request POST...) with the passing test.

Been stuck with this for a few days already any help/hint would be greatly appreciated.

**Comment by vinhboy** [comment]
I think I am having the same problem. I have a test like this

```
    it('should respond with 200', function(done) {
      request(app)
      .get('/foo')
      .expect('Content-Type', /json/)
      .expect(200,done)
    });
```

There is an `Unhandled rejection` in the `/foo` endpoint. I expect the test to fail telling me there is an `Unhandled rejection` error.

But it fails with

```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

I am not sure what to make of that. I am calling `done` in my `.expect`.

Shouldn't it know the request failed and be done?

**Comment by NKjoep** [comment]
@vinhboy have you tried with `async`?

it('should respond with 200', **async** function(done) { ....
