### ISSUE TITLE
Support Jasmine-node continuous testing

### ISSUE THREAD

**Issue by davidshen84** [visionmedia/supertest#43]
[Jasmine](http://pivotal.github.com/jasmine/) has the **--autotest** option which can continuously execute the test as the files are changing. **supertest** works fine when the test first start. But when I changed my test file, and save, **supertest** failed to release the address, and cause below error:

```
Error: listen EADDRINUSE
at errnoException (net.js:769:11)
at Server._listen2 (net.js:909:14)
at listen (net.js:936:10)
at Server.listen (net.js:985:5)
at Test.serverAddress (C:\proxy\node_modules\supertest\lib\test.js:63:18)
at new Test (C:\proxy\node_modules\supertest\lib\test.js:42:12)
```

Please add a _close_, or _stop_ method so the user can choose when to release the address.

**Comment by marcofranssen** [comment]
How to deal with this with mocha and gulp. I'm suffering the same issue.
