### ISSUE TITLE
.end() method is not called

### ISSUE THREAD

**Issue by poojasingh14** [visionmedia/supertest#430]
I am using supertest 3.0.0.
The control is not going inside .end method. Please let me know in which situations this happens?

    supertest(app)
    .post(URL)
    .set(header)
    .attach(payload)
    .end((err, res) => {
      if (err) {
        done(err);
      }
      done();
    });

**Comment by JakubSimandl** [comment]
Any update on this?

**Comment by kepikoi** [comment]
I made a small repo to test for this exact issue and express still doesn't quit on `3.3.0` https://github.com/kepikoi/supertest-issue-430

```
PS C:\www\supertest-issue-430> npm test

> tape-express@1.0.0 test C:\www\supertest-issue-430
> tape index.spec.js

listening on port 3301
TAP version 13
# /test should reply with 200
ok 1 /test replied with 200
not ok 2 failed to shut down express
  ---
    operator: fail
    at: Timeout.setTimeout [as _onTimeout] (C:\www\supertest-issue-430\index.spec.js:21:11)
    stack: |-
      Error: failed to shut down express
          at Test.assert [as _assert] (C:\www\supertest-issue-430\node_modules\tape\lib\test.js:224:54)
          at Test.bound [as _assert] (C:\www\supertest-issue-430\node_modules\tape\lib\test.js:76:32)
          at Test.fail (C:\www\supertest-issue-430\node_modules\tape\lib\test.js:317:10)
          at Test.bound [as fail] (C:\www\supertest-issue-430\node_modules\tape\lib\test.js:76:32)
          at Timeout.setTimeout [as _onTimeout] (C:\www\supertest-issue-430\index.spec.js:21:11)
          at ontimeout (timers.js:424:11)
          at tryOnTimeout (timers.js:288:5)
          at listOnTimeout (timers.js:251:5)
          at Timer.processTimers (timers.js:211:10)
  ...
npm ERR! Test failed.  See above for more details.
```
