### ISSUE TITLE
set hostname test failing

### ISSUE THREAD

**Issue by mikelax** [visionmedia/supertest#480]
Overview
===
With the release of v3.1.0, we introduced a failing test case. 
The test case is:  `should set request hostname`

The test is timing out, implying the done function isn't being called, I took a quick look at the test case and the only change I *thought* needed to be made was to instead return the error, ie: change `done();` on line 835 to `return done(err);` but this doesn't fix the issue.

**Comment by phawxby** [comment]
Finding the same issue in our test implementations. We have a node application that responds to multiple different domains in different ways so need to be able to set a host.

**With host**
```
await agent
      .host('www.foo.com')
      .get('/')
      .expect(301)
      .expect('location', 'foo');
```

Result
```
  ● homepage supertest

    connect ETIMEDOUT 23.214.140.73:57457
```

**Without host**
```
await agent
      //.host('www.foo.com')
      .get('/')
      .expect(301)
      .expect('location', 'foo');
```

Result
```
  ● homepage supertest

    expected 301 "Moved Permanently", got 404 "Not Found"

      at Test.Object.<anonymous>.Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test.Object.<anonymous>.Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.Object.<anonymous>.Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
```

**Comment by phawxby** [comment]
Ah-ha. Maybe I'm just using supertest wrong, this works!

```
  await request(app)
      .get('/')
      .set('Host', 'www.foo.com')
      .expect(301)
      .expect('location', 'foo');
```

**Comment by hiepnm** [comment]
> Ah-ha. Maybe I'm just using supertest wrong, this works!
> 
> ```
>   await request(app)
>       .get('/')
>       .set('Host', 'www.foo.com')
>       .expect(301)
>       .expect('location', 'foo');
> ```

It run ok on my local, but failed on CI.
