### ISSUE TITLE
superagent `pipe` is broken when using supertest

### ISSUE THREAD

**Issue by kirbysayshi** [visionmedia/supertest#49]
I have a fix, but need an opinion before submitting.

Doing something like:

``` js
supertest.get('/path/to/file.mp3')
  .buffer(false)
  .pipe(new _Speaker()) 
  .end(function(err, res){
    console.log('all done');
  })
```

Fails with:

```
/Users/drewp/dev/link-pipes/node_modules/supertest/lib/test.js:197
  fn(null, res);
  ^
TypeError: undefined is not a function
    at Test.assert (/Users/drewp/dev/link-pipes/node_modules/supertest/lib/test.js:197:3)
    at Test.end (/Users/drewp/dev/link-pipes/node_modules/supertest/lib/test.js:126:10)
    at Test.Request.callback (/Users/drewp/dev/link-pipes/node_modules/supertest/node_modules/superagent/lib/node/index.js:575:3)
    at Test.<anonymous> (/Users/drewp/dev/link-pipes/node_modules/supertest/node_modules/superagent/lib/node/index.js:133:10)
    at Test.EventEmitter.emit (events.js:96:17)
    at ClientRequest.Request.end (/Users/drewp/dev/link-pipes/node_modules/supertest/node_modules/superagent/lib/node/index.js:693:12)
    at ClientRequest.EventEmitter.emit (events.js:126:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1569:7)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
    at Socket.socketOnData [as ondata] (http.js:1472:20)
```

If I replace `this.end()` in line 384 of superagent/lib/node/index.js with `this.end(noop)`, everything works as expected. 

I've tracked this down but am not sure the best way to fix it. The issue is due to inheritance.

`Request.pipe` calls `this.end()...` (no args). `Request.end` checks for a passed `fn` or defaults to `noop`. But `end` is redefined in supertest to blindly call `this.assert(res, fn)`, which always assumes `fn` is defined. So `this.end` in `Request.pipe` is actually calling `Test.end`.

I could fix this by editing either supertest or superagent, but I'm not sure of the intended behavior. If I were to change supertest so that assert's `fn` param was optional, that would fix all of this, but then assert wouldn't be relaying the results anywhere. Changing this is superagent requires all calls to `this.end` to always pass `noop`, which feels weird considering this only happens because supertest subclasses `Request`.

So perhaps the best thing to do is allow `fn` to be optional in `Test.assert`?

**Comment by kristjanmik** [comment]
Any updates on this?

**Comment by kirbysayshi** [comment]
Nope. I haven't looked at supertest since I started this... is it still an issue?

**Comment by kristjanmik** [comment]
@kirbysayshi Yeah :/

**Comment by npkumar** [comment]
+1

**Comment by julienw** [comment]
FWIW I believe this is still an issue...
