### ISSUE TITLE
Mocha Supertest Express: app.address is not a function even if I exported correctly app.

### ISSUE THREAD

**Issue by Danver97** [visionmedia/supertest#497]
Good morning.
I'm still considering quite a newbe in Node.Js since very often I get into problems that with a bit of searching I figure out how to solve. Except this.

This is my `./src/app.js` file:
```javascript
const express = require('express');
const bodyParser = require('body-parser');
const ENV = require('./env');
const request = require('supertest');
const app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

app.get('/', (req, res) => {
    res.json({
        service: 'user-service',
    });
});

// This works correctly
const req = request(app);
req
    .get('/')
    .expect('Content-Type', /json/)
    .expect(JSON.stringify({
        service: 'user-service'
    }))
    .expect(200)
    .end(function (err, res) {
        if (err) throw err;
    });

// I tired in both ways
module.exports = Object.assign({}, app);
// module.exports = app;
```

This is my `./index.js` file:
```javascript
const app = require('./src/app');
const ENV = require('./src/env');

app.listen(3000, () => {
    console.log(`Server started on port ${ENV.port}`);
});

module.exports = app;
```

This is my `./test/test.js` file:
```javascript
const request = require('supertest');
const app = request('../src/app');
/*
  using request('http://localhost:3000') works correctly
  but i know it's not the best way to setup a testing environment
*/
//const req = request('http://localhost:3000'); 
const req = request(app);

describe('Integration test exaple', function() {
    it('get /', function(done) {
        req
        .get('/')
        .expect('Content-Type', /json/)
        .expect(JSON.stringify({ service: 'user-service' }))
        .expect(200, done);
    });
});
```

I tried to require `app` both from `app.js` and `index.js` but the result it's the same:
```shell
>> mocha ./test/test

  Integration test exaple
    1) get /

  0 passing (9ms)
  1 failing

  1) Integration test exaple
       get /:
     TypeError: app.address is not a function
      at Test.serverAddress (node_modules\supertest\lib\test.js:55:18)
      at new Test (node_modules\supertest\lib\test.js:36:12)
      at Object.obj.(anonymous function) [as get] (node_modules\supertest\index.js:25:14)
      at Context.<anonymous> (test\integration.test.js:12:10)
```

Thanks in advance for any kind of help!

**Comment by jonathansamines** [comment]
@Danver97 Exporting ´Object.assign({}, app)´ would never work because it will convert your `app` (which is a function) into an object. Are you sure it isn't working by just exporting the app instance? 

Besides that, you can alternatively export the result of `app.listen` from your index file to export the Http server instance, which should work as expected on your integration test

Hope it helps.

**Comment by Danver97** [comment]
@jonathansamines 
It's pretty curious: I checked again and using `module.exports = app` doesn't work, **BUT** in another project it's working fine...
Also using the result of `app.listen` doesn't work.
I can't understand why...

**Comment by jonathansamines** [comment]
@Danver97 Could you provide an isolated running test case for this? I could help figuring out what is wrong.

**Comment by Danver97** [comment]
@jonathansamines 
Sorry, what do you mean?
This is my code right now:
`./src/app.js`
```javascript
const express = require('express');
const jwt = require('jsonwebtoken');

const ENV = require('./env');
const usrManager = require('../modules/userManager');
const User = require('../models/user');

const app = express();


app.get('/', (req, res) => {
    res.json({
        service: 'user-service',
    });
});

module.exports = app;
```

`./test/integration.test.js`
```javascript
const request = require('supertest');
const jwt = require('jsonwebtoken');
const ENV = require('../src/env');
const app = request('../src/app');
const req = request(app);

describe('Integration test exaple', function() {
    const user = {
        username: 'pippo',
        email: 'pippo@gmail.com',
        password: 'pippopassword',
        name: 'pippo',
    }
    
    it('get /', function(done) {
        req
        .get('/')
        .set('Accept', 'application/json')
        .expect('Content-Type', /json/)
        .expect(JSON.stringify({ service: 'user-service' }))
        .expect(200, done);
    });
});
```

**Comment by Danver97** [comment]
@jonathansamines 
Here you are: https://github.com/Danver97/user-service

**Comment by jonathansamines** [comment]
@Danver97 Not sure how I didn't notice that before but the problem is that you are using the function `request` to try to require your app in your tests. You should use `require` instead.

See: https://github.com/Danver97/user-service/blob/master/test/integration.test.js#L4

**Comment by Danver97** [comment]
@jonathansamines Oh god. I can't believe it. How could I do something like that? That was a really stupid mistake!
Thank you so much for your time. Really appreciated!

**Comment by daryazata** [comment]
@Danver97 anyway thanks for asking this, did the same mistake--
