### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by alexec** [visionmedia/supertest#544]
I'm getting the following error when the response is HTML. HTML is an acceptable test scenario.

Could be with superagent rather than supertest?

```
     SyntaxError: Unexpected token < in JSON at position 0
      at JSON.parse (<anonymous>)
      at IncomingMessage.res.on (node_modules/superagent/lib/node/parsers/json.js:11:35)
      at endReadableNT (_stream_readable.js:1129:12)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by alexec** [comment]
Quite possibly. However, even if the server returns garbage, I feel like I should be able to parse and assert on it.

**Comment by rimiti** [comment]
You're right @blascsi.
Thanks for helping @alexec 🚀
