### ISSUE TITLE
Stacked assertions fail due to api inconsistency

### ISSUE THREAD

**Issue by DavidIAm** [visionmedia/supertest#55]
When attempting to execute this test:

request(app)
.get('/report/all')
.redirects(1)
.set('Accept', 'application/json')
.expect('Content-Type', /json/)
.end(function (err, res) { ...custom jasmine assertions here... } );

I get this error:

node_modules/supertest/lib/test.js:186
    actual = res.header[field.toLowerCase()];
                ^
TypeError: Cannot read property 'header' of null
    at Test.assert (node_modules/supertest/lib/test.js:186:17)
    at Test.end (node_modules/supertest/lib/test.js:124:10)
    at Test.assert (node_modules/supertest/lib/test.js:196:3)
    at Test.end (node_modules/supertest/lib/test.js:124:10)
    at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:575:3)
    at Test.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:133:10)
    at Test.EventEmitter.emit (events.js:93:17)
    at IncomingMessage.Request.end (node_modules/supertest/node_modules/superagent/lib/node/index.js:705:12)
    at IncomingMessage.EventEmitter.emit (events.js:123:20)
    at IncomingMessage._emitEnd (http.js:366:10)

My best understanding from analysis is that the the previous assert is passing through to another assert, but the input to the end event/method is just the response (res) and the input to whatever is passed through includes the error (err, res) making the inconsistency of the api causing the issue.  (perhaps a small wrapper for the first call inserting a null error after revising the api to consistently be err, res would do the job)

**Comment by DavidIAm** [comment]
Uh... thanks for nothing, rimiti?  Do you have *any* justification for closing this?

**Comment by rimiti** [comment]
@DavidIAm This issue has been created the 29 Mar 2013...

Can you tell me if the bug persist ?
