### ISSUE TITLE
supertest 4.x.x throws if not HTTP/200

### ISSUE THREAD

**Issue by karlismelderis** [visionmedia/supertest#559]
this stopped working for us after upgrade to 4.0.0
```js
const response = await request(app).get(path);
expect(response.status).toBe(500);
expect(response.body).toMatchSnapshot();
```

now it's throwing an error
```js
Internal Server Error

      at Test.Object.<anonymous>.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:804:15)
      at parser (node_modules/supertest/node_modules/superagent/lib/node/index.js:1036:18)
      at IncomingMessage.res.on (node_modules/supertest/node_modules/superagent/lib/node/parsers/json.js:19:7)
```

**Comment by rimiti** [comment]
Thank you for feedback. 🙏 

Please, check the related PR: #558

**Comment by rimiti** [comment]
#558 merged, I close this issue. 

Thank you 🙏
