### ISSUE TITLE
Can't get my test to work

### ISSUE THREAD

**Issue by fgisslen** [visionmedia/supertest#630]
Hi,
I am trying to get the tests for my express api to work.
If I create a simple test it's passing but I get this warning:
"A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks."

If I ran with that flags I get this error:

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPSERVERWRAP

      61 | 
    > 62 | app.listen(port, () => {
         |     ^
      63 |   console.log("Server started on port " + port);
      64 | });
      65 | module.exports = app;

      at Function.listen (node_modules/express/lib/application.js:618:24)
      at Object.<anonymous> (app.js:62:5)

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Connected to databasemongodb://xxx:xxx@xxxx.mlab.com:1xxxx/xxxx-sand".

      12 | mongoose.connect(config.database, { useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false, useCreateIndex:true});
      13 | mongoose.connection.on('connected', () => {
    > 14 |   console.log('Connected to database' + config.database);
         |           ^
      15 | });
      16 | mongoose.connection.on('error', (err) => {
      17 |   console.log('Database error ' + err);

      at BufferedConsole.log (node_modules/@jest/console/build/BufferedConsole.js:199:10)
      at NativeConnection.<anonymous> (app.js:14:11)
      at NativeConnection.set (node_modules/mongoose/lib/connection.js:125:12)
      at node_modules/mongoose/lib/connection.js:795:24
      at executeCallback (node_modules/mongodb/lib/operations/execute_operation.js:74:5)
      at node_modules/mongodb/lib/operations/connect.js:210:7
      at connectCallback (node_modules/mongodb/lib/operations/connect.js:375:5)
      at node_modules/mongodb/lib/operations/connect.js:611:5
      at Object.callback (node_modules/mongodb/lib/core/sdam/topology.js:297:43)

the test just looks like this:

const request = require('supertest')
const app = require('../app')
describe('GET /test', function() {
  it('responds with json', (done) => {
    request(app)
      .get('/test')
      .set('Accept', 'application/json')
      .expect(200)
      .end(function(err, res) {
        if (err) return done(err);
        done();
      });
  });
});

And the interesting code in the app.js is:

mongoose.Promise = global.Promise;
mongoose.connect(config.database, { useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false, useCreateIndex:true});
mongoose.connection.on('connected', () => {
  console.log('Connected to database' + config.database);
});
mongoose.connection.on('error', (err) => {
  console.log('Database error ' + err);
});

const app = express();
app.listen(port, () => {
  console.log("Server started on port " + port);
});
module.exports = app;

**Comment by fgisslen** [comment]
Hi again,
I solved it.

moved app.listen out of app.js and made mogoose async.
